force-app/main/default/objects/CaseCreatorEvent__e/CaseCreatorEvent__e.object-meta.xml
<CustomObject>
    <description>This Platform Event is subscribed inside salesforce ,and whenever the  customer priority 
becomes high it creates a case for technical support resolution.</description>
    <label>Case Creator Event</label>
    <pluralLabel>Case Creator Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CaseCreatorEvent__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>This field is used to hold the account Id for case creation</description>
    <label>Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This used to hold the description of the case</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This used to hold the event source</description>
    <label>Origin</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>This field holds the priority of the case should be created</description>
    <label>Priority</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>This used to hold subject for the case</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseCreationEventUtitily.cls
public with sharing class CaseCreationEventUtitily {

    public static final String CASES_OBJECT = 'Case';
    public static final String DEFAULT_QUEUE_NAME = 'InternalSupport_Queue';

    private static Id defaultQueueId;
    private static Id assignmentRuleId;

    // Query Assignment Rule or Default Queue assigns only once per execution
    static {
        initializeDefaults();
    }

    /**
    * @description: initializations metthods
    * @author:Aravind
    * @params:N/A
    **/
    private static void initializeDefaults() {
        //using Coalescing Operator  to skip the list has no rows to assign Errors
        AssignmentRule ar = [SELECT Id FROM AssignmentRule WHERE SobjectType = :CASES_OBJECT AND Active = TRUE LIMIT 1] ?? null;
        assignmentRuleId = ar != null ? ar.Id : null;

        // If no assignment rule, fetch default queue
        if (assignmentRuleId == null || Test.isRunningTest()) {
            QueueSobject defaultQueue = [SELECT QueueId FROM QueueSobject WHERE SobjectType = :CASES_OBJECT 
                                        AND Queue.DeveloperName = :DEFAULT_QUEUE_NAME LIMIT 1] ?? null;
            defaultQueueId = defaultQueue != null ? defaultQueue.QueueId : null;
        }

    }

    /**
    * @description: create case based on the published events
    * @author:Aravind
    * @params:caseEventList
    **/
    public static void createCaseBasedOnEvent(List<CaseCreatorEvent__e> caseEventList) {
        //no try catch blocks as exceptions are handled in run time
        if (caseEventList == null || caseEventList.isEmpty()) return; 

        List<Case> caseList = new List<Case>();
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.optAllOrNone = false;

        if (assignmentRuleId != null) {
            dmlOpts.assignmentRuleHeader.assignmentRuleId = assignmentRuleId;
        }

        for (CaseCreatorEvent__e caseEvent : caseEventList) {
            Case caseobj=new Case();
            caseobj.AccountId = caseEvent.AccountId__c;
            caseobj.Subject = caseEvent.Subject__c;
            caseobj.Description = caseEvent.Description__c;
            caseobj.Origin = caseEvent.Origin__c;
            caseobj.Priority = caseEvent.Priority__c;
            if(defaultQueueId != null){
               caseobj.OwnerId=defaultQueueId;
            }
            caseList.add(caseobj);
        }

        if (!caseList.isEmpty()) {
            List<Database.SaveResult> srList = Database.insert(caseList, dmlOpts);
            logErrors(srList, caseList);
        }
    }

    /**
    * @description: log errors on the case creation
    * @author:Aravind
    * @params:caseEventList
    **/
    private static void logErrors(List<Database.SaveResult> srList, List<Case> caseList) {
        for (Integer i = 0; i < srList.size(); i++) {
            if (!srList[i].isSuccess() && i < caseList.size()) {
                Database.Error error = srList[i].getErrors().get(0);
                System.debug('Error on Account Id ' + caseList[i].AccountId + ' - ' + error.getMessage());
            }
        }
    }
}