force-app/main/default/objects/PlacesFromPostalCode__c/PlacesFromPostalCode__c.object-meta.xml
<CustomObject>
    <description>This Object used to hold the postal codes, country and its places</description>
    <label>Places From Postal Code</label>
    <nameField>
        <displayFormat>PFPO-{0000000}</displayFormat>
        <label>Places  From Postal Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places From Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlacesFromPostalCode__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>This used to hold the external Id</description>
    <externalId>true</externalId>
    <inlineHelpText>This used to hold the external Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GetInfoFromZipCode_LT.cls
public with sharing class GetInfoFromZipCode_LT {

    /**
    * @description: This method used to return zip code data from API to LWC
    * @author:Aravind
    * @params:countryCode,zipCode
    **/
    @AuraEnabled(cacheable=true)
    public static Map<string,Object> getZipCodeData(String countryCode,string zipCode){
        try{
            return ExternalCalloutResultHandler.getZipCodeData(countryCode,zipCode);
        }
        catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }      
    }

    /**
    * @description: This method used Upsert the places data to the DB
    * @author:Aravind
    * @params:placeRecords
    **/
    @AuraEnabled
    public static void upsertPlaces(List<PlacesFromPostalCode__c> placeRecords){
        try{
            upsert placeRecords External_Id__c;
        }catch(Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }
}