force-app/main/default/objects/Account/fields/Risk__c.field-meta.xml
<CustomField>
    <fullName>Risk__c</fullName>
    <description>This custom field is used to highlight if the account is at risk.</description>
    <inlineHelpText>This custom field is used to highlight if the account is at risk.</inlineHelpText>
    <label>Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/CaseCreatorEvent__e.object-meta.xml
<CustomObject>
    <description>This Platform Event is subscribed inside salesforce ,and whenever the  customer priority 
becomes high it creates a case for technical support resolution.</description>
    <label>Case Creator Event</label>
    <pluralLabel>Case Creator Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CaseCreatorEvent__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>This field is used to hold the account Id for case creation</description>
    <label>Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This used to hold the description of the case</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This used to hold the event source</description>
    <label>Origin</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>This field holds the priority of the case should be created</description>
    <label>Priority</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>This used to hold subject for the case</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggersTest.cls
@isTest
private with sharing class AccountTriggersTest {
    private static string username='AccountTriggersTest'+System.currentTimeMillis()+'@company.com';
    private static string email='AccountTriggersTest'+System.currentTimeMillis()+'@gmail.com';

    @testSetup static void setup() {
        // Create common test accounts
        user u=UseCaseRelatedTestDataFactory.insertUser(username,email);
        system.runAs(u){
            UseCaseRelatedTestDataFactory.createMultipleAccounts();
        }
          
    }

    @isTest static void testFailedEventsWithFail() {
        User testUser=[Select Id from User where LastName='useCaseTester' limit 1];

        system.runAs(testUser){
            List<CaseCreationEventFailure.CaseEventInfo> cbDataLst=new List<CaseCreationEventFailure.CaseEventInfo>();
            Account acc=[Select Id from Account limit 1];
            CaseCreatorEvent__e caseEvent=(CaseCreatorEvent__e) CaseCreatorEvent__e.sObjectType.newSObject(null, true);
            caseEvent.AccountId__c=acc.Id;
            caseEvent.Origin__c= 'InternalAccount';
            caseEvent.Priority__c='High';   
            caseEvent.Subject__c='helo';
            caseEvent.Description__c='hello hello'; 
            CaseCreationEventFailure.CaseEventInfo cb=new CaseCreationEventFailure.CaseEventInfo(caseEvent.EventUuid,caseEvent.AccountId__c);
            cbDataLst.add(cb);

            Test.startTest();
                EventBus.publish(caseEvent, new CaseCreationEventFailure(cbDataLst));
                Test.getEventBus().fail(); 
            Test.stopTest();

            List<Task> tasklist=[Select id from Task where WhatId=:acc.Id];
            Assert.isTrue(tasklist.size()!=0);

        }
    }

    @isTest static void testAccountUpdateWithPublishEvent(){

        User testUser=[Select Id from User where LastName='useCaseTester' limit 1];

        system.runAs(testUser){

           List<Account> accList=[Select Id,Risk__c from Account limit 2];
           set<Id> accIdset=new Set<Id>();

           for(Account acc:accList){
             acc.Risk__c='High';
             accIdset.add(acc.Id);
           }

           Test.startTest();
             update accList;
             Test.getEventBus().deliver();
           Test.stopTest();

           List<Case> caseList=[Select id From Case where AccountId In:accIdset];

           Assert.isTrue(caseList.size()!=0);
        }
    }

    @isTest static void testExceptionOnAccountMethods(){

        User testUser=[Select Id from User where LastName='useCaseTester' limit 1];

        system.runAs(testUser){
            List<Account> accList=[Select Id from Account limit 2];
            try{
                Test.startTest();
                    AccountTriggerUtility.createCaseOnHighPriorityAccounts(accList,null);
                Test.stopTest();
            }
            catch(Exception ex){
                Assert.isNotNull(ex);
            }
        }
    }
}