force-app/main/default/objects/Account/fields/Risk__c.field-meta.xml
<CustomField>
    <fullName>Risk__c</fullName>
    <description>This custom field is used to highlight if the account is at risk.</description>
    <inlineHelpText>This custom field is used to highlight if the account is at risk.</inlineHelpText>
    <label>Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlacesFromPostalCode__c/PlacesFromPostalCode__c.object-meta.xml
<CustomObject>
    <description>This Object used to hold the postal codes, country and its places</description>
    <label>Places From Postal Code</label>
    <nameField>
        <displayFormat>PFPO-{0000000}</displayFormat>
        <label>Places  From Postal Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Places From Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlacesFromPostalCode__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>This field is used hold the countries across the world.</description>
    <inlineHelpText>This field is used hold the countries across the world.</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius, and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlacesFromPostalCode__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>This field used to hold the country code</description>
    <inlineHelpText>This field used to hold the country code</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AX</fullName>
                <label>Åland</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bosnia and Herzegovina</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Burkina Faso</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <label>Burundi</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Saint Barthélemy</label>
            </value>
            <value>
                <fullName>BM</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Brunei</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BQ</fullName>
                <label>Bonaire, Sint Eustatius, and Saba</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>CD</fullName>
                <label>DR Congo</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlacesFromPostalCode__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>This used to hold the external Id</description>
    <externalId>true</externalId>
    <inlineHelpText>This used to hold the external Id</inlineHelpText>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PlacesFromPostalCode__c/fields/PlaceName__c.field-meta.xml
<CustomField>
    <fullName>PlaceName__c</fullName>
    <description>This field used to hold place Name of the object</description>
    <label>Place Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlacesFromPostalCode__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>This is used to hold the postal code for places object</description>
    <inlineHelpText>This is used to hold the postal code for places object</inlineHelpText>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlacesFromPostalCode__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>In this  field we will store statue</description>
    <inlineHelpText>In this  field we will store statue</inlineHelpText>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PlacesFromPostalCode__c/fields/StateAbbreviation__c.field-meta.xml
<CustomField>
    <fullName>StateAbbreviation__c</fullName>
    <description>This holds the state Abbreviaition</description>
    <label>State Abbreviation</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UseCaseRelatedTestDataFactory.cls
@isTest
public with sharing class UseCaseRelatedTestDataFactory {
    private static final string LANG_EN_US='en_US';
    private static final string EMAILENCODING_KEY='utf-8';
    private static final string TIMEZONESID_KEY='Asia/Kolkata';

    /**
    * @description: This method is used to mock user creation
    * @author:Aravind
    * @params:userName,email
    **/
    public static User insertUser(String userName,String email){
       
        user u;
        try{
            Profile profile=[select id from profile where name='System Administrator' limit 1];
            Id userRoleId=[select Id from UserRole where DeveloperName ='CEO' limit 1]?.Id;

            u=new user();
            u.FirstName='TestUser1';
            u.LastName='useCaseTester';
            u.ProfileId=profile.id;
            u.Email=email;
            u.Username=userName;
            u.UserRoleId=userRoleId;
            u.LocaleSidKey=LANG_EN_US;
            u.EmailEncodingKey=EMAILENCODING_KEY;
            u.TimeZoneSidKey=TIMEZONESID_KEY;
            u.LanguageLocaleKey=LANG_EN_US;
            u.Alias=userName.left(8);
            u.CommunityNickname=userName.left(20);
            insert u;
        }
        catch(exception e){
        }

        return u;
       
    }

    /**
    * @description: This method is used to mock bulk Account creation
    * @author:Aravind
    * @params:N/A
    **/
    public static void createMultipleAccounts(){
        List<Account> testAccts = new List<Account>();
        for(Integer i=0;i<2;i++) {
            testAccts.add(new Account(Name = 'TestAcct'+i, 
                                      Risk__c='Low',
                                      Description='This is a very important account',
                                      AccountNumber='CD'+System.currentTimeMillis()+i));
        }
        insert testAccts;      
    }

    /**
    * @description: This method is used to mock PlacesFromPostalCode__c
    * @author:Aravind
    * @params:N/A
    **/
    public static PlacesFromPostalCode__c createPlacesFromPostalCode(){
        PlacesFromPostalCode__c place =new PlacesFromPostalCode__c();
        place.PostalCode__c='90210';
        place.Country__c='United States';
        place.CountryCode__c='US';
        place.PlaceName__c='Beverly Hills';
        place.State__c='California';
        place.StateAbbreviation__c='CA';
        place.PlaceLocation__Latitude__s=34.0901;
        place.PlaceLocation__Longitude__s=-118.4065;
        place.External_Id__c= 'BeverlyHills-US-90210-California';
        return place;
    }
}