force-app/main/default/objects/Account/fields/Risk__c.field-meta.xml
<CustomField>
    <fullName>Risk__c</fullName>
    <description>This custom field is used to highlight if the account is at risk.</description>
    <inlineHelpText>This custom field is used to highlight if the account is at risk.</inlineHelpText>
    <label>Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/CaseCreatorEvent__e.object-meta.xml
<CustomObject>
    <description>This Platform Event is subscribed inside salesforce ,and whenever the  customer priority 
becomes high it creates a case for technical support resolution.</description>
    <label>Case Creator Event</label>
    <pluralLabel>Case Creator Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CaseCreatorEvent__e/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>This field is used to hold the account Id for case creation</description>
    <label>Account ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This used to hold the description of the case</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>This used to hold the event source</description>
    <label>Origin</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>This field holds the priority of the case should be created</description>
    <label>Priority</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseCreatorEvent__e/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>This used to hold subject for the case</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerUtility.cls
public with sharing class AccountTriggerUtility {

    public static final string ORIGINFORCASE='InternalAccount';
    public static final string IMPACTED='Impacted';
    public static final string HYPEN='-';
    public static final string HIGH='High';
    public class CustomException extends Exception {}

    /**
    * @description: This method is used to publish PE whenever the Risk is High
    * @author:Aravind
    * @params:accList,accMap
    **/
    public static void createCaseOnHighPriorityAccounts(List<Account> accList, Map<Id,Account> accMap){

        try{
            List<CaseCreatorEvent__e> caseEventList=new List<CaseCreatorEvent__e>();
            //CaseCreationEventFailure is to call the failure callback when the even has failed in the event bus
            List<CaseCreationEventFailure.CaseEventInfo> cbDataLst=new List<CaseCreationEventFailure.CaseEventInfo>();
            // using a wrapper instead of map for faster execution and reduced heap size

            for(Account currAcc:accList){ 
                Account oldAcc=accMap.get(currAcc.Id);
                if(currAcc.Risk__c==HIGH && currAcc.Risk__c!=oldAcc.Risk__c){
                    CaseCreatorEvent__e caseEvent=(CaseCreatorEvent__e) CaseCreatorEvent__e.sObjectType.newSObject(null, true);
                    caseEvent.AccountId__c=currAcc.Id;
                    caseEvent.Origin__c= ORIGINFORCASE;
                    caseEvent.Priority__c=currAcc.Risk__c;   
                    caseEvent.Subject__c=currAcc.AccountNumber+HYPEN+IMPACTED;
                    caseEvent.Description__c=currAcc.Description; 
                    caseEventList.add(caseEvent); 
                    CaseCreationEventFailure.CaseEventInfo cbInfo=new CaseCreationEventFailure.CaseEventInfo(caseEvent.EventUuid,currAcc.Id);
                    cbDataLst.add(cbInfo);
                }    
            }   
            if(caseEventList.size()>0){
                List<Database.SaveResult> srList=EventBus.publish(caseEventList,new CaseCreationEventFailure(cbDataLst));    
            }
        }
        catch(Exception ex){
            throw new CustomException('error :'+ex.getMessage());
        }        
    }
}